### ISSUE TITLE
Error in result_fetch(res@ptr, n) : Error fetching buffer:

### ISSUE THREAD

**Issue by RobinEllison** [r-dbi/RMariaDB#69]
I installed this package according to the guide(My os is centos7).
Then i run the following command.
```
> library(DBI)
> library(RMariaDB)
> con <- dbConnect(RMariaDB::MariaDB(),username="root",password="123456",dbname="plant")
> con
<MariaDBConnection>
  Host:    localhost
  Server:  10.2.8-MariaDB
  Client:  10.2.8
> dbListTables(con)
Error in result_fetch(res@ptr, n) : Error fetching buffer: 
>
```

**Comment by krlmlr** [comment]
Thanks. I can't replicate this problem. Can you run `dbGetQuery(con, "SHOW TABLES")` or `dbSendQuery(conn, "SHOW TABLES")` ?

**Comment by james-atkins** [comment]
I too get this error on MacOS 10.13.

With database settings changed:

``` r
library(RMariaDB)

con <- dbConnect(MariaDB(), host = "db.example.com", user = "user", dbname = "database")
con
#> <MariaDBConnection>
#>   Host:    db.example.com
#>   Server:  5.0.92-log
#>   Client:  10.2.9

dbListTables(con)
#> Error in result_fetch(res@ptr, n): Error fetching buffer:

dbGetQuery(con, "SHOW TABLES")
#> Error in result_fetch(res@ptr, n): Error fetching buffer:

rs <- dbSendQuery(con, "SHOW TABLES")
rs
#> <MariaDBResult>
#>   SQL  SHOW TABLES
#>   ROWS Fetched: 0 [incomplete]
#>        Changed: 0
dbFetch(rs)
#> Error in result_fetch(res@ptr, n): Error fetching buffer:
dbClearResult(rs)

devtools::session_info()
#> Warning in as.POSIXlt.POSIXct(Sys.time()): unknown timezone 'default/
#> Europe/London'
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, darwin17.0.0        
#>  ui       unknown                     
#>  language (EN)                        
#>  collate  en_GB.UTF-8                 
#>  tz       <NA>                        
#>  date     2017-10-25
#> Packages -----------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.1.1   2017-09-25 CRAN (R 3.4.1)
#>  base      * 3.4.2   2017-09-29 local         
#>  bit         1.1-12  2014-04-09 CRAN (R 3.4.2)
#>  bit64       0.9-7   2017-05-08 CRAN (R 3.4.2)
#>  compiler    3.4.2   2017-09-29 local         
#>  datasets  * 3.4.2   2017-09-29 local         
#>  DBI         0.7     2017-06-18 CRAN (R 3.4.0)
#>  devtools    1.13.3  2017-08-02 CRAN (R 3.4.1)
#>  digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)
#>  graphics  * 3.4.2   2017-09-29 local         
#>  grDevices * 3.4.2   2017-09-29 local         
#>  hms         0.3     2016-11-22 CRAN (R 3.4.0)
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
#>  knitr       1.17    2017-08-10 CRAN (R 3.4.1)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
#>  methods   * 3.4.2   2017-09-29 local         
#>  Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.1)
#>  RMariaDB  * 1.0-2   2017-10-04 CRAN (R 3.4.2)
#>  rmarkdown   1.6     2017-06-15 CRAN (R 3.4.0)
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)
#>  stats     * 3.4.2   2017-09-29 local         
#>  stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)
#>  tools       3.4.2   2017-09-29 local         
#>  utils     * 3.4.2   2017-09-29 local         
#>  withr       2.0.0   2017-07-28 CRAN (R 3.4.0)
#>  yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```

**Comment by ivanp84** [comment]
Slackware (64 bit current from October 10th) same problem:

```
> dbListTables(con)
Error in result_fetch(res@ptr, n) : Error fetching buffer: 
```

```
> dbGetQuery(con, "SHOW TABLES")
Error in result_fetch(res@ptr, n) : Error fetching buffer: 
```

RMariaDB installed just now, R version 3.4.2 (2017-09-28),
MariaDB -> mysql  Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1.

Database for now has only one table (with approx 130000 records).

**Comment by krlmlr** [comment]
Thanks. Can you please call `RMariaDB:::init_logging("VERB")` before running the query, and post results?

**Comment by ivanp84** [comment]
Meanwhile, I updated MariaDB to 10.2.10, but the err is still there... Here is the output (with entire workaround, to distinguish if I had something wrong):
```

> library(DBI)
> con <- dbConnect(RMariaDB::MariaDB(), user="ivan", password="123456", dbname="inep")
> RMariaDB:::init_logging("VERB")
> dbListTables(con)
MariaResultPrep::send_query@32: SHOW TABLES
MariaResultPrep::send_query@43: 0
MariaResultPrep::execute@76: 
MariaResultPrep::cache_metadata@241: 
MariaResultPrep::cache_metadata@253: 0 -> Tables_in_inep(253, 0) => string
MariaRow::setup@23: 
MariaRow::setup@36: 0 -> string
MariaRow::setup@92: 0
MariaRow::setup@93: 0
MariaRow::setup@94: 0x2356860
MariaRow::setup@95: 0x3ad0680
MariaRow::setup@96: 
MariaRow::setup@97: 0x2ae27a0
MariaRow::setup@105: 0
MariaRow::setup@106: 0
MariaRow::setup@107: 0x2356860
MariaRow::setup@108: 0x3ad0680
MariaRow::setup@109: 
MariaRow::setup@110: 0x2ae27a0
MariaResultPrep::step@125: 
MariaResultPrep::fetch_row@141: 
MariaResultPrep::fetch_row@147: 101
MariaResultPrep::step@136: 1
MariaRow::fetch_buffer@219: 13
MariaRow::fetch_buffer@228: 13
MariaRow::fetch_buffer@229: 0x3b429b0
MariaRow::fetch_buffer@230: 0x2356860
MariaRow::fetch_buffer@231: 0x3ad0680
MariaRow::fetch_buffer@232: 
MariaRow::fetch_buffer@233: 0x2ae27a0
MariaRow::fetch_buffer@236: 1
Error in result_fetch(res@ptr, n) : Error fetching buffer: 
> 
```

**Comment by krlmlr** [comment]
Thanks. Can you please show the output of:

```r
con
devtools::session_info()
```

? I suspect the issue might resolve if you build RMariaDB against the MySQL libraries.

**Comment by ivanp84** [comment]
Here it is:

```

> con
<MariaDBConnection>
  Host:    localhost
  Server:  10.2.10-MariaDB
  Client:  10.2.10
> 
> devtools::session_info()
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  C                           
 tz       <NA>                        
 date     2017-11-05                  

Packages ----------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.2   2017-10-06 local         
 bit         1.1-12  2014-04-09 CRAN (R 3.4.2)
 bit64       0.9-7   2017-05-08 CRAN (R 3.4.2)
 compiler    3.4.2   2017-10-06 local         
 datasets  * 3.4.2   2017-10-06 local         
 DBI       * 0.7     2017-06-18 CRAN (R 3.4.2)
 devtools  * 1.13.3  2017-08-02 CRAN (R 3.4.2)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.2)
 graphics  * 3.4.2   2017-10-06 local         
 grDevices * 3.4.2   2017-10-06 local         
 hms         0.3     2016-11-22 CRAN (R 3.4.2)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.2)
 methods   * 3.4.2   2017-10-06 local         
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)
 RMariaDB    1.0-2   2017-10-04 CRAN (R 3.4.2)
 stats     * 3.4.2   2017-10-06 local         
 tcltk       3.4.2   2017-10-06 local         
 tools       3.4.2   2017-10-06 local         
 utils     * 3.4.2   2017-10-06 local         
 withr       2.1.0   2017-11-01 CRAN (R 3.4.2)
> 
```

I didn't understand exactly, should I get MySQL libraries..? I grabbed Slackware packages for MariaDB from Slack repo, and Pat did a great work there to produce it 100 % Maria and Slack compatible. I think that doing that chimeric work with MySQL libraries there is a great chance to make system unstable. I have experienced that with Qt5 libs years ago, that was disaster... Somehow solution could be userspace and not system changes, but then, that is a magnitude work for a minute benefits.

**Comment by krlmlr** [comment]
On Ubuntu it's possible to install MySQL and MariaDB client libraries alongside, not sure about Slackware. I'd like to recommend MariaDB client libraries, because they're actively developed, but I had some difficulties with using the prepared statement protocol in some library versions (#60, #61, #62). This is why RMariaDB currently uses MySQL client libraries if they are available.

What do I need to do to replicate what you're seeing in a Docker container or virutal machine?

**Comment by krlmlr** [comment]
Also, can you please share the output of `mariadb_config` on your system?

**Comment by krlmlr** [comment]
One more thing to try: Can you please clone the RMariaDB repo and run `devtools::test()` in an R session there? You may need to tweak `tests/testthat/helper-DBItest.R`, the second argument to `make_context()` is a list of arguments to `dbConnect()`. (We're looking into simpler ways of running these tests in r-dbi/DBI#200.)

**Comment by ivanp84** [comment]
mariadb_config:

```
Copyright 2011-2015 MariaDB Corporation AB
Get compiler flags for using the MariaDB Connector/C.
Usage: mariadb_config [OPTIONS]
  --cflags        [-I/usr/include/mysql -I/usr/include/mysql/mysql]
  --include       [-I/usr/include/mysql -I/usr/include/mysql/mysql]
  --libs          [-L/usr/lib64/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --libs_r        [-L/usr/lib64/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --libs_sys      [-lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --version       [10.2.10]
  --cc_version    [3.0.2]
  --socket        [/var/run/mysql/mysql.sock]
  --port          [3306]
  --plugindir     [/usr/lib64/mysql/plugin]
  --tlsinfo       [OpenSSL 1.0.2l]
```

For the devtools:::test(), I feel pretty stupid at this point (this could be due my kidney issue I recently developed, it's just awful :@), but I cannot catch what I should do with that, as far as I tried to run that test in RMariaDB branch on my hdd, but that form is compiled after install.packages... Should I grab source and workaround in that manner? Sincerely apologies if this consultations was dummy enough to make tinny black hole in some faraway galaxy :p I tried first option but it didn't anything and cannot cope what next? You are just at completely different level, I'm facing one of those moments when you feels like "just a user" :)

**Comment by krlmlr** [comment]
Thanks. Yes, my instructions were a bit brief ;-)

1. Please clone RMariaDB to a directory on your computer, or [download](https://github.com/r-dbi/RMariaDB/archive/master.zip) and extract a .zip archive.
2. In this directory, start R
3. In R, run `install.packages("devtools")`
3. In R, run `devtools::install_deps(dependencies = TRUE)`
4. Edit `tests/testthat/helper-DBItest.R` as necessary, the second argument to `make_context()` contains a list of arguments you would normally pass to `dbConnect()`
5. In R, run `devtools::test()`

The output of the last step is very helpful for me, please don't hesitate to get back with any further questions.

**Comment by ivanp84** [comment]
I think that I have edited properly:

```
DBItest::make_context(
  MariaDB(),
  list(user="ivan", password="123456", dbname = "inep"),
  tweaks = DBItest::tweaks(
    constructor_relax_args = TRUE,
    placeholder_pattern = "?",
    logical_return = function(x) as.integer(x),
    list_temporary_tables = FALSE
  ),
  name = "RMariaDB")

```

Now, there are results:

```
> devtools::test()
Loading RMariaDB
Testing RMariaDB
DBItest[RMariaDB]: Getting started: ...........
DBItest[RMariaDB]: Driver: ..............................................................1.......................
 *** caught segfault ***
address 0x630000006d, cause 'memory not mapped'

Traceback:
 1: .Call(`_RMariaDB_connection_create`, host, user, password, db,     port, unix_socket, client_flag, groups, default_file, ssl_key,     ssl_cert, ssl_ca, ssl_capath, ssl_cipher)
 2: connection_create(host, username, password, dbname, as.integer(port),     unix.socket, as.integer(client.flag), groups, default.file,     ssl.key, ssl.cert, ssl.ca, ssl.capath, ssl.cipher)
 3: .local(drv, ...)
 4: dbConnect(<S4 object of class "MariaDBDriver">, user = "ivan",     password = "phd2017", dbname = "inep")
 5: dbConnect(<S4 object of class "MariaDBDriver">, user = "ivan",     password = "phd2017", dbname = "inep")
 6: connect_fun()
 7: connect(ctx)
 8: withVisible(code)
 9: expect_visible(connect(ctx))
10: withCallingHandlers(code, warning = function(condition) {    out$push(condition)    invokeRestart("muffleWarning")})
11: capture_warnings(object)
12: expect_warning(con <- expect_visible(connect(ctx)), NA)
13: eval(code, test_env)
14: eval(code, test_env)
15: withCallingHandlers(eval(code, test_env), expectation = handle_expectation,     skip = handle_skip, warning = handle_warning, message = handle_message,     error = handle_error)
16: doTryCatch(return(expr), name, parentenv, handler)
17: tryCatchOne(expr, names, parentenv, handlers[[1L]])
18: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
19: doTryCatch(return(expr), name, parentenv, handler)
20: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
21: tryCatchList(expr, classes, parentenv, handlers)
22: tryCatch(withCallingHandlers(eval(code, test_env), expectation = handle_expectation,     skip = handle_skip, warning = handle_warning, message = handle_message,     error = handle_error), error = function(e) {}, skip = function(e) {})
23: test_code(desc, code, env = parent.frame())
24: test_that("DBItest[RMariaDB]: Driver: can_connect", {    expect_warning(con <- expect_visible(connect(ctx)), NA)    expect_warning(expect_s4_class(con, "DBIConnection"), NA)    expect_warning(dbDisconnect(con), NA)})
25: test_fun(ctx)
26: FUN(X[[i]], ...)
27: vapply(seq_along(tests), function(test_idx) {    test_name <- names(tests)[[test_idx]]    if (skip_flag[[test_idx]])         FALSE    else {        test_fun <- patch_test_fun(tests[[test_name]], paste0(test_context,             ": ", test_name))        test_fun(ctx)    }}, logical(1L))
28: run_tests(ctx, spec_driver, skip, test_suite)
29: test_driver(skip = skip, ctx = ctx)
30: DBItest::test_all(c("get_info_driver", "get_info_connection",     "data_logical", "data_raw", "get_info_result", NULL))
31: eval(exprs, env)
32: eval(exprs, env)
33: source_file(path, new.env(parent = env), chdir = TRUE)
34: force(code)
35: with_reporter(reporter = reporter, start_end_reporter = start_end_reporter,     {        lister$start_file(basename(path))        source_file(path, new.env(parent = env), chdir = TRUE)        end_context()    })
36: FUN(X[[i]], ...)
37: lapply(paths, test_file, env = env, reporter = current_reporter,     start_end_reporter = FALSE, load_helpers = FALSE)
38: force(code)
39: with_reporter(reporter = current_reporter, results <- lapply(paths,     test_file, env = env, reporter = current_reporter, start_end_reporter = FALSE,     load_helpers = FALSE))
40: test_files(paths, reporter = reporter, env = env, ...)
41: (function (path, filter = NULL, reporter = "summary", env = test_env(),     ...) {    source_test_helpers(path, env)    paths <- find_test_scripts(path, filter, ...)    test_files(paths, reporter = reporter, env = env, ...)})("/home/ivan/Documents/Inep/2017/R/RMariaDB-master/tests/testthat",     filter = NULL, env = <environment>)
42: do.call(testthat::test_dir, testthat_args)
43: force(code)
44: withr::with_envvar(r_env_vars(), do.call(testthat::test_dir,     testthat_args))
45: devtools::test()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 2
Save workspace image? [y/n/c]: n
Warning messages:
1: Unknown tweaks: list_temporary_tables 
2: Unknown tweaks: list_temporary_tables 
[1]+  Done                    emacs helper-DBItest.R
bash-4.4$ 

```

Hope you'll find something in this output :) 
I'll give a chance MySQL libs, but ones I have found for Slack probably were obsoleted, migration to MariaDB happened long ago.

**Comment by krlmlr** [comment]
Thanks. That's the worst thing we could have expected -- a segmentation fault :-(

How can I replicate your setup on a local Slackware machine?

**Comment by ivanp84** [comment]
I even dind't noticed *segfault*, just copied... that is sad, seems like some malloc problem... :-( 
My Slack is pretty clean Slackware 64bit -current [https://mirrors.slackware.com/slackware/slackware64-current/](https://mirrors.slackware.com/slackware/slackware64-current/), just recently setup to the current. MariaDB comes with Slack, and R I compiled from source. System installation still doing it in old-fashion way, get current folder via ftp, then make bootable usb stick, and install the system from it. MariaDB works perfectly. The db 'inep' is pretty large one, with patients biochemistry parameters, though not that big in today's terms. Maybe that could be helpful, here is fields descriptions for one table:

```
MariaDB [inep]> DESCRIBE pacijenti2011;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| broj_prokola    | int(11)          | YES  |     | NULL    |                |
| Datum           | varchar(300)     | NO   |     | NULL    |                |
| Ime             | varchar(100)     | NO   |     | NULL    |                |
| Prezime         | varchar(100)     | NO   |     | NULL    |                |
| Godina_rodjenja | varchar(50)      | NO   |     | NULL    |                |
| JMBG            | varchar(100)     | NO   |     | NULL    |                |
| Analiza_sifra   | varchar(50)      | NO   |     | NULL    |                |
| Analiza_naziv   | varchar(300)     | NO   |     | NULL    |                |
| Normativ        | varchar(500)     | NO   |     | NULL    |                |
| Jedinica        | varchar(300)     | NO   |     | NULL    |                |
| Nalaz           | varchar(300)     | NO   |     | NULL    |                |
| Napomena        | varchar(300)     | NO   |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)

```

**Comment by mjiCunningham** [comment]
I'm seeing the same error on OpenSuse Tumbleweed with 
Server:  10.2.11-MariaDB
Client:  10.2.6

Interestingly, if I request numeric data (including dates) then everything works. 
Any request for a VARCHAR or CHAR returns an error, even if cast to a fixed length or specific character set
Casting the character fields to an INT returns a valid result set, although clearly no useful data.

I'd be very grateful for any ideas.

Mike

**Comment by lepennec** [comment]
I'm having the same issue won Fedora 27. Please let me known how I can help.

**Comment by krlmlr** [comment]
Thanks. I can only guess, but maybe installing the latest MariaDB Connector/C from source might work? Version 2.3.4 contains a bug fix that is crucial for RMariaDB: https://mariadb.com/kb/en/library/mariadb-connector-c-234-release-notes/

**Comment by lepennec** [comment]
I'm using MariaDB 3.0.2... I'm pretty sure this is a memory related issue. I'm trying to understand why the buffer reallocation in fetch_buffer is not working, so far without success.

**Comment by krlmlr** [comment]
Connector/C 3.0.2 doesn't seem to have the fix for that issue, but then I'm not sure if it's necessary there: https://jira.mariadb.org/browse/CONC-281. Anyway, it still might be worthwhile to try 2.3.4. I'll try to test different connector versions myself, too.

**Comment by lepennec** [comment]
I've try with MariaDB 3 10.2.11 which includes the patch without success.

**Comment by krlmlr** [comment]
Thanks. I'm still confused with MariaDB version numbers, do you know how to translate the 10.2.11 to the Connector/C version?

**Comment by lepennec** [comment]
It seems that the Connector is available either as a standalone or as part of mariadb. The version associated to MariaDB 10.2.11 is a version of the Connector/C 3.0.2 in which the patch has been applied...

**Comment by krlmlr** [comment]
Thanks again. Is there a list that defines this association? How do you see that the patch has been applied in 3.0.2? (According to the release notes, the version is too young for that patch...)

**Comment by lepennec** [comment]
The only way I've been able to see this was to browse the source code on github (or to download the corresponding file on mariad db website). The version of the connector appears in libmariadb//CMakeLists.txt... Unfortunately, some patches have been applied without any modification of the version number. One can look at the code of mariadb_stmt.cpp to see that the patch has been applied...

**Comment by krlmlr** [comment]
I see:

- https://github.com/MariaDB/server/tree/c3b641ee20f49c8850c4c02056c120dc17a5eeb6 is the state of the server sources where the version has been bumped to 10.2.11
- the `libmariadb` directory links to https://github.com/MariaDB/mariadb-connector-c/tree/7e53ab369815590ff92913b581d43eb7786f2fe2
- that already contains the relevant patch in https://github.com/MariaDB/mariadb-connector-c/commit/17110fb9298fb328759bef287ceb72f97cc81a04

I remember successfully connecting a Fedora Docker container to my local MySQL instance for #53, need to remember how I did it ;-)

**Comment by krlmlr** [comment]
Doing it the other way round now: Installed Connector/C sources locally from https://github.com/MariaDB/mariadb-connector-c/tree/10.2-server, seeing test failures. Will investigate.

Thanks for your input!

**Comment by krlmlr** [comment]
Just verified: MariaDB installed and running with Connector/C 2.3.4 from https://github.com/MariaDB/mariadb-connector-c/commit/4bbcced passes all tests.

**Comment by krlmlr** [comment]
Can you please try the pull request?

```r
# install.packages("remotes")
remotes::install_github("r-dbi/RMariaDB#81")
```

**Comment by lepennec** [comment]
I still have the same issue.

**Comment by krlmlr** [comment]
This is strange, can you please post a reprex with logging enabled?

I've filed an issue upstream: https://jira.mariadb.org/browse/CONC-301.

**Comment by lepennec** [comment]
```
library(DBI)
con <- dbConnect(RMariaDB::MariaDB(),
                  host = "sql11.freemysqlhosting.net",
                 port = 3306,
                 dbname = "sql11211642",
                 username = "sql11211642",
                 password = "lEssE7CPhY")
RMariaDB:::init_logging("VERB")
dbGetQuery(con, "SELECT height FROM people")
dbGetQuery(con, "SELECT * FROM people")
```

**Comment by krlmlr** [comment]
Thanks. What does the output look like?

**Comment by krlmlr** [comment]
This has been confirmed to be a problem with Connector/C, fixed in 2.3.5, 3.0.3, and probably the upcoming version of MariaDB. Will close when a version with the bug fix has been released.

**Comment by jtelleriar** [comment]
MariaDB Server can work either with MySQL Connector or MariaDB Connector.

So maybe it would be worth to install the MySQL C# Connector.

MySQL in comparison with MariaDB nowadays is quite outdated due to Oracle's total lack of updated; but MySQL Connectors are just fine.

**Comment by jtelleriar** [comment]
Another option would be to patiently wait till MariaDB Connector #C 3.0.3 of course, but if still does not work, Connector could be moved to Oracle's

**Comment by lepennec** [comment]
Please feel free to close this issue. I will use one of the proposed solution until Connector 3.0.3 is released

**Comment by jtelleriar** [comment]
Yes, both new connector versions have been released today.

Great news! :)

Thank you all.
Juan

**Comment by krlmlr** [comment]
Closed in #92 (for Windows), need to keep in mind that Connector/C 2.3.5 or 3.0.3 are required for best results on other platforms.

**Comment by thomhickey** [comment]
I'm still getting this using MariaDB 10.3.7 on macOS High Sierra. mariadb_config tells me I have cc_version 3.0.5. I'm connecting from RMariaDB 1.0.6. Any ideas? Doesn't matter what I do, I always get same:

Error in result_fetch(res@ptr, n = n) : Error fetching buffer:
Calls: dbGetQuery ... .local -> dbFetch -> dbFetch -> .local -> result_fetch

**Comment by zbessette** [comment]
@thomhickey Hi Thom, I'm running into the same problems as you described above, but I' having a little bit of trouble replicating one of your steps. I uninstalled MariaDB and installed MySQL-devel-5.6.41-1.el7.x86_64.rpm. The only sticking point is exactly what symlinks you made exactly. Without them I get the following error on the instal of RMariaDB: 
```g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o RMariaDB.so DbConnection.o DbResult.o MariaBinding.o MariaResultImpl.o MariaResultPrep.o MariaResultSimple.o MariaRow.o MariaTypes.o MariaUtils.o RcppExports.o connection.o driver.o result.o -L/usr/lib64 -lmysqlclient -lpthread -lm -ldl -L/usr/lib64/R/lib -lR
/usr/bin/ld: cannot find -lmysqlclient```

**Comment by thomhickey** [comment]
@zbessette Hello Zyon ... Here are my notes on the build:

[root@server mysql]# yum list installed | grep -i maria
MariaDB-client.x86_64      10.2.14-1.el7.centos    @mariadb
MariaDB-common.x86_64      10.2.14-1.el7.centos    @mariadb
MariaDB-compat.x86_64      10.2.14-1.el7.centos    @mariadb
MariaDB-devel.x86_64       10.2.15-1.el7.centos    @mariadb
MariaDB-server.x86_64      10.2.14-1.el7.centos    @mariadb
MariaDB-shared.x86_64      10.2.15-1.el7.centos    @mariadb

[root@server mysql]# yum list installed | grep -i mysql

yum remove MariaDB-server, client, devel, compat

yum install MySQL-devel-5.6.41-1.el7.x86_64.rpm

cd /usr/lib64
  684  ln -s mysql/libmysqlclient.a libmysqlclient.a
  686  ln -s mysql/libmysqlclient_r.a libmysqlclient_r.a
  687  ln -s mysql/libmysqlservices.a libmysqlservices.a

Build RMariaDB.so

Then remove the MySQL-devel package and re-install MariaDB.

Hope that helps! If not, I am happy to send the binary, but that's always a risky maneuver :)

**Comment by zbessette** [comment]
@thomhickey Thanks for the help, those steps worked perfectly. You definitely saved me quite the headache.

**Comment by thomhickey** [comment]
@zbessette wonderful, glad that worked for you too.

**Comment by verajosemanuel** [comment]
Same error here on Mac OS Mojave

**Comment by FAMILIALP** [comment]
el mismo error pero corro R con Windows 10 a 64 bit sobre una conexión a base de datos Oracle 11g
